// Export pages
export '/login/login/login_widget.dart' show LoginWidget;
export '/inicio/inicio_cliente/clase_principal/clase_principal_widget.dart'
    show ClasePrincipalWidget;
export '/perfil/perfil/perfil_widget.dart' show PerfilWidget;
export '/login/registrar/registrar_widget.dart' show RegistrarWidget;
export '/citas/visual_citas/vista_calendario/vista_calendario_widget.dart'
    show VistaCalendarioWidget;
export '/citas/visual_citas/vista_modificar/vista_modificar_widget.dart'
    show VistaModificarWidget;
export '/citas/visual_citas/vista_cancelar/vista_cancelar_widget.dart'
    show VistaCancelarWidget;
export '/empleados/crud_empleado/crear_empleado/crear_empleado_widget.dart'
    show CrearEmpleadoWidget;
export '/empleados/crud_empleado/modificar_empleado/modificar_empleado_widget.dart'
    show ModificarEmpleadoWidget;
export '/empleados/crud_empleado/deshabilitar_empleado/deshabilitar_empleado_widget.dart'
    show DeshabilitarEmpleadoWidget;
export '/empleados/crud_empleado/buscar_empleados/buscar_empleados_widget.dart'
    show BuscarEmpleadosWidget;
export '/empleados/visual_empleados/vista_historial_empleado/vista_historial_empleado_widget.dart'
    show VistaHistorialEmpleadoWidget;
export '/inicio/inicio_admin/clase_empleado/clase_empleado_widget.dart'
    show ClaseEmpleadoWidget;
export '/inventario/crud_inventario/crear_inventario/crear_inventario_widget.dart'
    show CrearInventarioWidget;
export '/inventario/crud_vista/vista_invetario02/vista_invetario02_widget.dart'
    show VistaInvetario02Widget;
export '/inventario/crud_inventario/modificar_inventario/modificar_inventario_widget.dart'
    show ModificarInventarioWidget;
export '/inventario/crud_vista/vista_inventario/vista_inventario_widget.dart'
    show VistaInventarioWidget;
export '/inventario/vist_notis/agregado_correcto_inventario/agregado_correcto_inventario_widget.dart'
    show AgregadoCorrectoInventarioWidget;
export '/inventario/vist_notis/modificado_correcto_inventario/modificado_correcto_inventario_widget.dart'
    show ModificadoCorrectoInventarioWidget;
export '/inventario/crud_inventario/eliminar_inventarios/eliminar_inventarios_widget.dart'
    show EliminarInventariosWidget;
export '/inventario/crud_inventario/eliminar_inventario_seguro/eliminar_inventario_seguro_widget.dart'
    show EliminarInventarioSeguroWidget;
export '/inventario/vist_notis/eliminado_correcto_inventario/eliminado_correcto_inventario_widget.dart'
    show EliminadoCorrectoInventarioWidget;
export '/inventario/filtros_inventario/filtros_inventario_widget.dart'
    show FiltrosInventarioWidget;
export '/inventario/crud_inventario/gestion_estado_inventario/gestion_estado_inventario_widget.dart'
    show GestionEstadoInventarioWidget;
export '/inventario/crud_inventario/configurar_alertas_inventario/configurar_alertas_inventario_widget.dart'
    show ConfigurarAlertasInventarioWidget;
export '/inventario/crud_inventario/informacion_inventario/informacion_inventario_widget.dart'
    show InformacionInventarioWidget;
export '/citas/visual_citas/vista_cita/vista_cita_widget.dart'
    show VistaCitaWidget;
export '/citas/crud_citas/crear_cita/crear_cita_widget.dart'
    show CrearCitaWidget;
export '/citas/crud_citas/modificar_cita/modificar_cita_widget.dart'
    show ModificarCitaWidget;
export '/citas/crud_notas_medico/modificar_nota_medico/modificar_nota_medico_widget.dart'
    show ModificarNotaMedicoWidget;
export '/citas/crud_notas_medico/crear_nota_medico/crear_nota_medico_widget.dart'
    show CrearNotaMedicoWidget;
export '/inicio/inicio_cliente/especialidad/especialidad_widget.dart'
    show EspecialidadWidget;
export '/inicio/inicio_cliente/contactanos/contactanos_widget.dart'
    show ContactanosWidget;
export '/inicio/inicio_admin/clase_inventario/clase_inventario_widget.dart'
    show ClaseInventarioWidget;
export '/inicio/inicio_admin/clase_expediente/clase_expediente_widget.dart'
    show ClaseExpedienteWidget;
export '/inicio/inicio_medico/clase_expediente_medic/clase_expediente_medic_widget.dart'
    show ClaseExpedienteMedicWidget;
export '/citas/visual_nota_medico/vista_notas/vista_notas_widget.dart'
    show VistaNotasWidget;
export '/citas/visual_citas/vista_cita_medico/vista_cita_medico_widget.dart'
    show VistaCitaMedicoWidget;
export '/citas/visual_citas/vista_cita_admin/vista_cita_admin_widget.dart'
    show VistaCitaAdminWidget;
export '/expedientes/vista_expediente/vista_expediente_widget.dart'
    show VistaExpedienteWidget;
export '/expedientes/vistadebuscar_ex/vistadebuscar_ex_widget.dart'
    show VistadebuscarExWidget;
export '/inicio/inicio_medico/asignarpermisos/asignarpermisos_widget.dart'
    show AsignarpermisosWidget;
export '/inicio/inicio_medico/respaldo/respaldo_widget.dart'
    show RespaldoWidget;
export '/empleados/visual_empleados/ver_empleado/ver_empleado_widget.dart'
    show VerEmpleadoWidget;
export '/empleados/visual_empleados/eliminar_empleado/eliminar_empleado_widget.dart'
    show EliminarEmpleadoWidget;
export '/empleados/visual_empleados/evaluavion_empleado/evaluavion_empleado_widget.dart'
    show EvaluavionEmpleadoWidget;
export '/empleados/crud_empleado/crear_evaluacion_empleado/crear_evaluacion_empleado_widget.dart'
    show CrearEvaluacionEmpleadoWidget;
